---
- name: Check reboot-required flag
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: vm_healthcheck_reboot_stat

- name: Store reboot facts
  ansible.builtin.set_fact:
    vm_healthcheck_reboot_required: "{{ vm_healthcheck_reboot_stat.stat.exists | bool }}"
